#!/bin/sh

set -eu

PORT="${PORT:-"80"}"
HEALTH_CHECK_PATH="${HEALTH_CHECK_PATH:-"/health"}"

# If health check path is set to root (/), use /health instead
# root is not a valid health check path for this nginx configuration
if [ "$HEALTH_CHECK_PATH" = "/" ]; then
  HEALTH_CHECK_PATH="/health"
fi

tee /etc/nginx/conf.d/default.conf << 'EOF' >/dev/null
server {
    listen       ${PORT};
    listen  [::]:${PORT};
    server_name  localhost;

    #access_log  /var/log/nginx/host.access.log  main;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    # health check endpoint
    location ${HEALTH_CHECK_PATH} {
        access_log off;
        error_log   off;
        return 200 "healthy\n";
        add_header Content-Type text/plain;
    }
}
EOF

sed -i "s|\${PORT}|${PORT}|g" /etc/nginx/conf.d/default.conf
sed -i "s|\${HEALTH_CHECK_PATH}|${HEALTH_CHECK_PATH}|g" /etc/nginx/conf.d/default.conf

echo ""
echo "#####################"
echo "Nginx running on port $PORT"
echo "Healthcheck endpoint: $HEALTH_CHECK_PATH"
echo "#####################"
echo ""

nginx -g "daemon off;"
