# Start from the original image
FROM kale5/rickroll

# Expose the new port
EXPOSE 5173


# Expose the new port
EXPOSE 5173

# Update the Nginx configuration to use port 5173 instead of 8080
RUN sed -i 's/listen 8080;/listen 5173;/' /etc/nginx/conf.d/default.conf

# Set the container to run as intended by the original image
CMD ["nginx", "-g", "daemon off;"]
