# Start from the original image
FROM kale5/rickroll

# Remove the existing default.conf
RUN rm /etc/nginx/conf.d/default.conf

# Copy your custom default.conf into the container
COPY ./3000/default.conf /etc/nginx/conf.d/

# Expose the new port
EXPOSE 3000

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
